import { createHash } from 'node:crypto';
import { readdirSync, readFileSync } from 'node:fs';
import { defineConfig, type Plugin } from 'vite';

/**
 * Writes dist/sw.js, a service worker that keeps every file of this build on the device so the
 * app opens offline. The cache name changes with the build, so a new deploy replaces the old files.
 * Only the app's own files are cached; maps live in IndexedDB, never in this cache.
 */
function offlineCache(): Plugin {
  return {
    name: 'offline-cache',
    apply: 'build',
    generateBundle(_options, bundle) {
      const publicFiles = readdirSync(new URL('./public/', import.meta.url));
      // The page itself is cached as "/": Cloudflare redirects /index.html to /, and a redirected
      // response can't be used to answer a page navigation.
      const files = [
        '/',
        ...Object.keys(bundle).filter((f) => f !== 'index.html').map((f) => `/${f}`),
        ...publicFiles.map((f) => `/${f}`),
      ];
      const hash = createHash('sha256');
      for (const [name, chunk] of Object.entries(bundle)) {
        hash.update(name);
        hash.update(chunk.type === 'chunk' ? chunk.code : chunk.source);
      }
      for (const f of publicFiles) hash.update(readFileSync(new URL(`./public/${f}`, import.meta.url)));
      const version = hash.digest('hex').slice(0, 12);
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: serviceWorker(version, files) });
    },
  };
}

function serviceWorker(version: string, files: string[]): string {
  return `// Generated by vite.config.ts. Keeps the app's own files on the device for offline use.
const CACHE = 'map-layers-${version}';
const FILES = ${JSON.stringify(files)};
// Module scripts are requested with an Origin header the cached copies weren't stored with; a
// "Vary: Origin" response header would then stop them matching, so Vary is ignored.
const MATCH = { ignoreVary: true, ignoreSearch: true };

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('map-layers-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return;
  if (request.mode === 'navigate') {
    // Any page address opens the app from the cache, so it works with no connection.
    event.respondWith(caches.match('/', MATCH).then((cached) => cached || fetch(request)));
    return;
  }
  event.respondWith(caches.match(request, MATCH).then((cached) => cached || fetch(request)));
});
`;
}

export default defineConfig({
  build: {
    target: 'es2022',
  },
  plugins: [offlineCache()],
});
